# Generated by Django 3.0 on 2020-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('sub_judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
