# Generated by Django 3.0 on 2020-04-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daftar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=13)),
                ('alamat', models.TextField()),
                ('umur', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=1)),
                ('posisi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Daftar',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
    ]
