# Generated by Django 3.0 on 2020-04-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_daftar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar',
            name='buat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='image',
            field=models.ImageField(default='static/upload/tkg/', upload_to='static/upload/'),
        ),
    ]
