# Generated by Django 3.0 on 2020-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200408_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('isi', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='daftar',
            options={'verbose_name_plural': 'Data-Daftar'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Buat-Post'},
        ),
        migrations.AlterField(
            model_name='daftar',
            name='image',
            field=models.ImageField(default='upload/default-image.jpg', upload_to='upload/'),
        ),
    ]
