# Generated by Django 3.0 on 2020-04-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200409_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(blank=True, max_length=100, null=True)),
                ('pesan', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Data-Pesan',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Buat-Banner'},
        ),
        migrations.AlterField(
            model_name='daftar',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
