# Generated by Django 3.0 on 2020-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200411_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='upload/default-image.jpg', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='alamat',
            field=models.TextField(help_text='Masukkan alamat anda'),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='email',
            field=models.EmailField(help_text='Masukkan E-mail anda', max_length=254),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='gender',
            field=models.CharField(help_text='Jenis Kelamin anda', max_length=1),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='image',
            field=models.ImageField(default='upload/default-image.jpg', help_text='Masukkan foto anda', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='nama',
            field=models.CharField(help_text='Masukkan nama anda', max_length=200),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='posisi',
            field=models.CharField(help_text='Posisi tukang', max_length=50),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='telepon',
            field=models.CharField(help_text='Masukkannomor telepon anda', max_length=13),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='umur',
            field=models.CharField(help_text='Masukkan umur anda', max_length=3),
        ),
    ]
