# Generated by Django 3.0 on 2020-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200411_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='image',
            field=models.ImageField(default='upload/default-image.jpg', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='nama',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='posisi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='telepon',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='umur',
            field=models.CharField(max_length=3),
        ),
    ]
