# Generated by Django 3.0 on 2020-04-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200411_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daftar',
        ),
        migrations.DeleteModel(
            name='Pesan',
        ),
    ]
