# Generated by Django 3.0 on 2020-04-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_daftar_pesan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='daftar',
            name='posisi',
        ),
    ]
