# Generated by Django 3.0 on 2020-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200412_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftar',
            name='image',
        ),
        migrations.AlterField(
            model_name='daftar',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='posisi',
            field=models.CharField(max_length=50),
        ),
    ]
