# Generated by Django 3.0 on 2020-04-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200412_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('perusahaan', models.CharField(max_length=50)),
                ('estimasi', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Data-Request',
            },
        ),
    ]
