# Generated by Django 3.0 on 2020-04-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_minta'),
    ]

    operations = [
        migrations.AddField(
            model_name='minta',
            name='buat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
